### PR TITLE
For merge

### PR DESCRIPTION
**Pull request by athal7**
these are all of the changes from the bonobos fork to get master up to date so that this can get merged into spree core

### CODE REVIEW

**Comment by athal7** [comment]
ping @jdutil @peterberkenbosch if we are slow on getting store credits into core it could be good to get this work into master / a 2-4 branch

**Comment by JDutil** [comment]
Yea would be worth getting this stuff into a 2-4 branch, and included in the merge to master as well.  I'm not sure the current status of work on getting this into core.  Last I checked (and still appears to be) it was waiting on people to address the last few subtasks, and initial feedback on the PR.

**Comment by peterberkenbosch** [comment]
I can take over if needed, this should be in core asap IMHO.

**Comment by athal7** [comment]
@peterberkenbosch there are some gift card things here too which would be good to have even once store credits gets into core

**Comment by peterberkenbosch** [comment]
yes, I agree @athal7, I like the way you guys are using it. just have to make sure it's easy to extend. On my list for next week.

**Comment by athal7** [comment]
for sure, i meant good to have in this extension (have to maintain the gift card functionality even after store credits is pulled out)

**Pull request closed without merging**
