### PR TITLE
Add store credits seeds.

### PR DESCRIPTION
**Pull request by gmacdougall**
Without the seeds, things don't work correctly. If you run the
migrations this data will be added, but if a new developer/environment
is created from seeds then things don't work quite right.

### CODE REVIEW

**Comment by gmacdougall** [comment]
This has already been added to 2-3-stable and master.

@athal7 You should consider adding `SpreeStoreCredits::Engine.load_seed if defined?(SpreeStoreCredits::Engine)` to your db/seeds.rb in your spree install.

**Comment by athal7** [comment]
@gmacdougall i'm confused as to why the migrations don't add this data properly, can you say more?

**Comment by gmacdougall** [comment]
@athal7 The migrations do add the data properly. However, for new environments, we load the schema from seeds rather than running the entire chain of migrations. I reloaded my schema earlier, and seeded the database, and ran in to issues with this missing expected data.

**Comment by athal7** [comment]
@gmacdougall you are right. :+1:. we'll include this in our spree install.

**Pull request merged**
